// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * `LiveKitJsTransport` — the browser-side transport for Portal's wasm build.
 *
 * Implements the `JsTransport` contract that `livekit-portal-wasm`'s
 * `WasmPortal::connect` expects (`livekit-portal-wasm/src/transport.rs`):
 * one method per `PortalTransport` seam operation, promise-returning for
 * the async ones, with room events forwarded into the wasm-bound
 * `PortalEventSink`. All protocol decisions live in the Rust core — this
 * file is only the LiveKit room adapter.
 *
 * ```js
 * import { WasmPortalConfig, WasmPortal } from "./livekit_portal_wasm.js";
 * import { LiveKitJsTransport } from "./livekit-js-transport.js";
 *
 * const config = new WasmPortalConfig("teleop", "operator");
 * config.addStateField("j1.pos", "f32");
 * const portal = new WasmPortal(config);
 * const transport = new LiveKitJsTransport();
 * await portal.connect(transport, url, token);
 * ```
 *
 * # Video paths
 *
 * Robot WebRTC publish: `publishVideoFrame` lazily publishes a
 * canvas-backed track per declared track name; frames are painted via
 * `putImageData` + `requestFrame()`. WebRTC re-encodes and stamps its own
 * media clock, so the optional timestamp is ignored (parity: the native
 * encoder behaves the same way).
 *
 * Operator receive: WebRTC frames arrive as media tracks, not bytes. The
 * transport records subscribed tracks and notifies the sink; the embedder
 * decodes (`<video>` → canvas → `getImageData`) and pushes RGB through
 * `WasmPortal.ingestVideoFrame`, which feeds the same slots/sync-buffer
 * pipeline as the native receiver. Frame-video byte-stream tracks need no
 * decode loop on the operator side — they arrive as complete payloads via
 * `onByteStream`.
 *
 * # Error convention
 *
 * Rejections are `{code, message, data}` where they carry RPC semantics
 * (thrown `RpcError` from livekit-js satisfies this shape) and plain
 * `Error`s otherwise; the Rust adapter degrades unknown shapes to a
 * stringified message under the application-error code.
 */

import { Room, RoomEvent, RpcError, Track } from "livekit-client";
import type {
  ByteStreamReader,
  ByteStreamHandler,
} from "livekit-client";
import type { RemoteVideoTrack, RpcInvocationData } from "livekit-client";

/**
 * Byte payloads crossing the wasm boundary. wasm-bindgen hands over
 * `ArrayBuffer`-backed arrays, which also satisfies livekit-client's
 * `NonSharedUint8Array` parameter types.
 */
export type PortalBytes = Uint8Array<ArrayBuffer>;

/**
 * The event sink wasm hands to {@link LiveKitJsTransport.bindEventSink}
 * before `connect` resolves. Each method maps 1:1 onto a Rust
 * `TransportEvent`; the sink forwards into the channel Portal's event
 * loop drains. Callers must treat it as opaque — methods are generated by
 * wasm-bindgen.
 */
export interface PortalEventSink {
  onDataReceived(payload: PortalBytes, topic: string, sender: string | null): void;
  onByteStream(topic: string, sender: string, payload: PortalBytes): void;
  onVideoTrackSubscribed(trackName: string): void;
  onParticipantConnected(identity: string, attributes: Record<string, string>): void;
  onParticipantAttributesChanged(identity: string, attributes: Record<string, string>): void;
  onParticipantDisconnected(identity: string): void;
  onReconnected(): void;
  /**
   * Dispatch an inbound RPC invocation into the Rust handler. Resolve with
   * the handler's string result, or reject with `{code, message, data}`.
   */
  invokeRpcMethod(
    method: string,
    requestId: string,
    callerIdentity: string,
    payload: string,
    responseTimeoutMs: number,
  ): Promise<string>;
}

/** Mirrors the Rust `ConnectInfo` serde payload (`camelCase`). */
export interface ConnectInfo {
  url: string;
  token: string;
  /** Byte-stream topics Portal will consume; streams on other topics are dropped. */
  byteStreamTopics: string[];
}

/** The Rust `TransportRpcRequest` as serialized onto the JS boundary. */
export interface JsRpcRequest {
  destination: string;
  method: string;
  payload: string;
  /** Milliseconds, or `null` for the transport default. */
  responseTimeoutMs: number | null;
}

export interface JsParticipantInfo {
  identity: string;
  attributes: Record<string, string>;
}

/**
 * The JS-side transport contract consumed by `WasmPortal.connect`. Embedders
 * may implement it directly for non-LiveKit rooms; this file ships the
 * reference implementation over `livekit-client`.
 */
export interface JsTransport {
  connect(connectInfo: ConnectInfo): Promise<void>;
  disconnect(): Promise<void>;
  publishData(payload: PortalBytes, topic: string | null, reliable: boolean): Promise<void>;
  sendBytes(payload: PortalBytes, topic: string): Promise<void>;
  setAttributes(attributes: Record<string, string>): Promise<void>;
  performRpc(request: JsRpcRequest): Promise<string>;
  registerRpcMethod(method: string): void;
  unregisterRpcMethod(method: string): void;
  localIdentity(): string | null;
  localAttributes(): Record<string, string>;
  remoteParticipants(): JsParticipantInfo[];
  /**
   * WebRTC receivers are decoded by the embedder in the browser; `sink` is
   * always `null` here (native passes a real one into the Rust SDK).
   */
  startVideoReceiver(trackName: string, sink: null): void;
  publishVideoFrame(
    trackName: string,
    rgb: PortalBytes,
    width: number,
    height: number,
    timestampUs: number | null,
  ): Promise<void>;
  /** Called synchronously by wasm before the `connect` promise resolves. */
  bindEventSink(sink: PortalEventSink): void;
  sleep(ms: number): Promise<void>;
}

interface VideoPublisher {
  canvas: HTMLCanvasElement;
  ctx: CanvasRenderingContext2D;
  mediaTrack: CanvasCaptureMediaStreamTrack;
  published: boolean;
}

/** Fallback code for handler rejections without RPC semantics. */
const APPLICATION_ERROR = 1500;
/** LiveKit RPC `MethodNotFound`. */
const METHOD_NOT_FOUND = 1602;

/**
 * Reference `JsTransport` over a livekit-js {@link Room}.
 *
 * Lifecycle mirrors the native transport: `connect` wires events and joins
 * the room, everything else operates on the connected room, and
 * `disconnect` tears readers, published tracks, and handler registrations
 * down. Safe to call `disconnect` when never connected.
 */
export class LiveKitJsTransport implements JsTransport {
  private sink: PortalEventSink | null = null;
  private room: Room | null = null;
  private byteStreamTopics = new Set<string>();
  private abortControllers = new Set<AbortController>();
  /** RPC methods currently registered on the room (re-applied after reconnect). */
  private rpcMethods = new Set<string>();
  /** Methods registered before `connect` (buffered, applied at connect). */
  private pendingRpcMethods = new Set<string>();
  private videoPublishers = new Map<string, VideoPublisher>();
  private remoteVideoTracks = new Map<string, RemoteVideoTrack>();
  private activeVideoReceivers = new Set<string>();

  bindEventSink(sink: PortalEventSink): void {
    this.sink = sink;
  }

  async connect(connectInfo: ConnectInfo): Promise<void> {
    if (this.room) {
      throw new Error("LiveKitJsTransport is already connected");
    }
    const room = new Room();
    this.room = room;
    this.wireRoomEvents(room);

    for (const topic of connectInfo.byteStreamTopics) {
      // livekit-js routes byte streams per topic; topics outside this list
      // are never delivered — mirroring core's take-or-drop semantics.
      this.byteStreamTopics.add(topic);
      room.registerByteStreamHandler(topic, (reader, participantInfo) => {
        void this.readByteStream(reader, participantInfo.identity);
      });
    }

    // RPC methods registered before connect (or by Portal's reconnect
    // re-application) become live here.
    const pending = [...this.pendingRpcMethods];
    this.pendingRpcMethods.clear();
    for (const method of pending) {
      this.registerRpcMethodOnRoom(method);
      this.rpcMethods.add(method);
    }

    try {
      await room.connect(connectInfo.url, connectInfo.token);
    } catch (e) {
      this.detachRoom(room);
      throw e;
    }
  }

  async disconnect(): Promise<void> {
    const room = this.room;
    if (!room) {
      return;
    }
    for (const controller of this.abortControllers) {
      controller.abort();
    }
    this.abortControllers.clear();

    for (const publisher of this.videoPublishers.values()) {
      try {
        await room.localParticipant.unpublishTrack(publisher.mediaTrack, true);
      } catch (e) {
        console.warn("[portal-wasm] unpublish failed during disconnect", e);
      }
    }
    this.videoPublishers.clear();
    this.remoteVideoTracks.clear();
    this.activeVideoReceivers.clear();

    for (const method of this.rpcMethods) {
      room.unregisterRpcMethod(method);
    }
    this.rpcMethods.clear();
    for (const topic of this.byteStreamTopics) {
      room.unregisterByteStreamHandler(topic);
    }
    this.byteStreamTopics.clear();

    this.detachRoom(room);
    await room.disconnect();
  }

  async publishData(payload: PortalBytes, topic: string | null, reliable: boolean): Promise<void> {
    const options: Parameters<Room["localParticipant"]["publishData"]>[1] = { reliable };
    if (topic !== null && topic !== undefined) {
      options.topic = topic;
    }
    await this.localParticipant().publishData(payload, options);
  }

  async sendBytes(payload: PortalBytes, topic: string): Promise<void> {
    // compress: false — the native path never compresses byte streams, and
    // per-frame deflate would add latency to the 60 Hz frame-video path.
    await this.localParticipant().sendBytes(payload, { topic, compress: false });
  }

  async setAttributes(attributes: Record<string, string>): Promise<void> {
    await this.localParticipant().setAttributes(attributes);
  }

  async performRpc(request: JsRpcRequest): Promise<string> {
    const lp = this.localParticipant();
    return lp.performRpc({
      destinationIdentity: request.destination,
      method: request.method,
      payload: request.payload,
      responseTimeout: request.responseTimeoutMs ?? undefined,
    });
  }

  registerRpcMethod(method: string): void {
    if (!this.room) {
      this.pendingRpcMethods.add(method);
      return;
    }
    this.registerRpcMethodOnRoom(method);
    this.rpcMethods.add(method);
  }

  unregisterRpcMethod(method: string): void {
    this.pendingRpcMethods.delete(method);
    if (this.room && this.rpcMethods.delete(method)) {
      this.room.unregisterRpcMethod(method);
    }
  }

  localIdentity(): string | null {
    const identity = this.room?.localParticipant.identity;
    return identity ? identity : null;
  }

  localAttributes(): Record<string, string> {
    if (!this.room) {
      return {};
    }
    return { ...this.room.localParticipant.attributes };
  }

  remoteParticipants(): JsParticipantInfo[] {
    if (!this.room) {
      return [];
    }
    return [...this.room.remoteParticipants.values()].map((p) => ({
      identity: p.identity,
      attributes: { ...p.attributes },
    }));
  }

  startVideoReceiver(trackName: string, _sink: null): void {
    // Core calls this after it processes the VideoTrackSubscribed event, so
    // re-notifying the sink here would loop the event channel. Decoding is
    // the embedder's job (see module docs); record the subscription so
    // `getSubscribedVideoTrack` can serve it.
    this.activeVideoReceivers.add(trackName);
  }

  /**
   * The subscribed remote track for a declared video track name, or
   * `null` before subscription. The embedder's decode loop attaches this
   * to a `<video>`/canvas and pushes decoded RGB through
   * `WasmPortal.ingestVideoFrame`. Populated once core responds to the
   * subscription with `startVideoReceiver`.
   */
  getSubscribedVideoTrack(trackName: string): RemoteVideoTrack | null {
    return this.activeVideoReceivers.has(trackName)
      ? this.remoteVideoTracks.get(trackName) ?? null
      : null;
  }

  async publishVideoFrame(
    trackName: string,
    rgb: PortalBytes,
    width: number,
    height: number,
    // WebRTC stamps its own media clock; the sender timestamp has no
    // equivalent on the track path (byte-stream frame-video preserves it).
    _timestampUs: number | null,
  ): Promise<void> {
    if (rgb.length !== width * height * 3) {
      throw new Error(`publishVideoFrame: expected ${width * height * 3} RGB bytes, got ${rgb.length}`);
    }
    const publisher = this.publisherFor(trackName, width, height);
    const clamped = new Uint8ClampedArray(rgb.length);
    clamped.set(rgb);
    publisher.ctx.putImageData(new ImageData(clamped, width, height), 0, 0);
    if (!publisher.published) {
      await this.localParticipant().publishTrack(publisher.mediaTrack, { name: trackName });
      publisher.published = true;
    }
    publisher.mediaTrack.requestFrame();
  }

  async sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  // --- internals ---

  private localParticipant(): NonNullable<Room["localParticipant"]> {
    if (!this.room) {
      throw new Error("LiveKitJsTransport: not connected");
    }
    return this.room.localParticipant;
  }

  private detachRoom(room: Room): void {
    if (this.room === room) {
      this.room = null;
    }
  }

  private registerRpcMethodOnRoom(method: string): void {
    const room = this.room;
    if (!room) {
      return;
    }
    // Portal re-applies stored handlers on reconnect; livekit throws on a
    // duplicate registration, so replace instead.
    if (this.rpcMethods.has(method)) {
      room.unregisterRpcMethod(method);
    }
    room.registerRpcMethod(method, async (data: RpcInvocationData) => {
      const sink = this.sink;
      if (!sink) {
        throw new RpcError(METHOD_NOT_FOUND, "no event sink bound", undefined);
      }
      try {
        return await sink.invokeRpcMethod(
          method,
          data.requestId,
          data.callerIdentity,
          data.payload,
          data.responseTimeout,
        );
      } catch (e) {
        const err = e as { code?: number; message?: string; data?: string };
        throw new RpcError(
          err.code ?? APPLICATION_ERROR,
          err.message ?? String(e),
          err.data,
        );
      }
    });
  }

  private async readByteStream(reader: ByteStreamReader, identity: string): Promise<void> {
    const topic = reader.info.topic;
    const controller = new AbortController();
    this.abortControllers.add(controller);
    reader.signal = controller.signal;
    const parts: Uint8Array[] = [];
    try {
      for await (const chunk of reader) {
        parts.push(chunk);
      }
    } catch {
      // Aborted by disconnect, or the sender cancelled mid-stream: drop the
      // partial payload, matching the native reader's take-or-drop behavior.
      this.abortControllers.delete(controller);
      return;
    }
    this.abortControllers.delete(controller);
    const sink = this.sink;
    if (!sink || !this.byteStreamTopics.has(topic)) {
      return;
    }
    let total = 0;
    for (const part of parts) {
      total += part.length;
    }
    const payload = new Uint8Array(total);
    let offset = 0;
    for (const part of parts) {
      payload.set(part, offset);
      offset += part.length;
    }
    sink.onByteStream(topic, identity, payload);
  }

  private publisherFor(trackName: string, width: number, height: number): VideoPublisher {
    let publisher = this.videoPublishers.get(trackName);
    if (publisher && (publisher.canvas.width !== width || publisher.canvas.height !== height)) {
      publisher.canvas.width = width;
      publisher.canvas.height = height;
      publisher = { ...publisher, ctx: publisher.canvas.getContext("2d", { alpha: false })! };
    }
    if (!publisher) {
      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d", { alpha: false });
      if (!ctx) {
        throw new Error("LiveKitJsTransport: 2D canvas context unavailable");
      }
      // frameRequestRate 0: frames are pushed manually via requestFrame.
      const mediaTrack = canvas.captureStream(0).getVideoTracks()[0] as CanvasCaptureMediaStreamTrack;
      publisher = { canvas, ctx, mediaTrack, published: false };
      this.videoPublishers.set(trackName, publisher);
    }
    return publisher;
  }

  private wireRoomEvents(room: Room): void {
    room.on(RoomEvent.DataReceived, (payload, participant, _kind, topic) => {
      // Portal's protocol always topics its packets; untoped packets are
      // other participants' business.
      if (topic === undefined || topic === null) {
        return;
      }
      this.sink?.onDataReceived(payload, topic, participant?.identity ?? null);
    });

    room.on(RoomEvent.TrackSubscribed, (track, publication) => {
      if (track.kind !== Track.Kind.Video) {
        return;
      }
      const trackName = publication.trackName;
      this.remoteVideoTracks.set(trackName, track as RemoteVideoTrack);
      this.sink?.onVideoTrackSubscribed(trackName);
    });

    room.on(RoomEvent.TrackUnsubscribed, (_track, publication) => {
      this.remoteVideoTracks.delete(publication.trackName);
    });

    room.on(RoomEvent.ParticipantConnected, (participant) => {
      this.sink?.onParticipantConnected(participant.identity, { ...participant.attributes });
    });

    room.on(RoomEvent.ParticipantAttributesChanged, (_changed, participant) => {
      this.sink?.onParticipantAttributesChanged(participant.identity, { ...participant.attributes });
    });

    room.on(RoomEvent.ParticipantDisconnected, (participant) => {
      this.sink?.onParticipantDisconnected(participant.identity);
    });

    room.on(RoomEvent.Reconnected, () => {
      this.sink?.onReconnected();
    });
  }
}

/** Re-exported for embedders that type against the raw handler signature. */
export type { ByteStreamHandler };